// <auto-generated />
using System;
using InsuranceClaims.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceClaims.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InsuranceClaimsDbContext))]
    [Migration("20260929124500_AddClaimTypes")]
    partial class AddClaimTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceClaims.Domain.Entities.ClaimType", b =>
                {
                    b.Property<int>("Id").HasColumnType("int");
                    b.Property<int>("DisplayOrder").HasColumnType("int");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<string>("Name").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");
                    b.HasKey("Id");
                    b.HasIndex("Name").IsUnique();
                    b.ToTable("ClaimTypes", (string)null);
                    b.HasData(
                        new { Id = 1, Name = "Colisão", IsActive = true, DisplayOrder = 1 },
                        new { Id = 2, Name = "Roubo/Furto", IsActive = true, DisplayOrder = 2 },
                        new { Id = 3, Name = "Danos naturais", IsActive = true, DisplayOrder = 3 },
                        new { Id = 4, Name = "Incêndio", IsActive = true, DisplayOrder = 4 },
                        new { Id = 5, Name = "Terceiros", IsActive = true, DisplayOrder = 5 },
                        new { Id = 6, Name = "Vidros", IsActive = true, DisplayOrder = 6 },
                        new { Id = 7, Name = "Outros", IsActive = true, DisplayOrder = 7 });
                });

            modelBuilder.Entity("InsuranceClaims.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<string>("ClaimNumber").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<int>("ClaimTypeId").HasColumnType("int");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime?>("DeletedAt").HasColumnType("datetime2");
                    b.Property<string>("Description").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<decimal>("EstimatedAmount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.Property<string>("InsuredDocument").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
                    b.Property<string>("InsuredName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<DateTime>("OccurrenceDate").HasColumnType("date");
                    b.Property<string>("PolicyNumber").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("ClaimNumber").IsUnique();
                    b.HasIndex("ClaimTypeId");
                    b.ToTable("Claims", (string)null);
                });

            modelBuilder.Entity("InsuranceClaims.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<string>("Name").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<string>("NormalizedEmail").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("PasswordHash").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedEmail").IsUnique();
                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("InsuranceClaims.Domain.Entities.Claim", b =>
                {
                    b.HasOne("InsuranceClaims.Domain.Entities.ClaimType", "ClaimType")
                        .WithMany()
                        .HasForeignKey("ClaimTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClaimType");
                });
#pragma warning restore 612, 618
        }
    }
}
